name: CI

on:
  push:
    branches: [main]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci --prefer-offline --no-audit
      - run: npm run lint

  unit:
    name: Unit tests (Jest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci --prefer-offline --no-audit
      - run: npm run test:unit

  api:
    name: API tests (Playwright)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci --prefer-offline --no-audit
      - run: |
          npx playwright install --with-deps
          npm run test:api

  e2e:
    name: E2E (Desktop + Mobile)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci --prefer-offline --no-audit
      - run: npx playwright install --with-deps

      - name: Playwright E2E tests
        run: npm run test:e2e

      - name: Upload E2E report & traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-playwright-${{ github.run_id }}
          path: |
            playwright-report/
            test-results/e2e-desktop/
            test-results/e2e-mobile/
          retention-days: 14

  visual:
    name: Visual regression
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci --prefer-offline --no-audit
      - run: npx playwright install --with-deps

      - name: Playwright visual tests
        run: npm run test:visual

      - name: Upload visual diff images
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: visual-diffs-${{ github.run_id }}
          path: |
            test-results/visual/**/*.png
          retention-days: 14
